### PR TITLE
Fixed the actions and transformers

### PR DESCRIPTION
**Pull request by pbo-cirus**
This PR contains:

- Updates to latest Cloud-vision plugin.
- Update to Output schema.

Known Issues:

https://issues.cask.co/browse/PLUGIN-120

Errors in pipeline run on Sandbox environment only.

Note: Example pipelines are part of another PR.

### CODE REVIEW

**Comment by pbo-cirus** [comment]
@googlebot I signed it!

**Comment by bdmogal** [comment]
@pbo-cirus thanks a lot for creating separate PRs. Can you also please ensure that you use 2 spaced tabs, so that the diff does not include unnecessary changes?

**Comment by pbo-cirus** [comment]
I thought I did the spacing. Weird...

**Comment by pbo-cirus** [comment]
I used IntelliJ to use 2 spaces instead of 4 (default)

**Comment by pbo-cirus** [comment]
Bhooshan,

Are you able to review? I see the message from the Google bot asking about a CLA. I already have signed it but I keep seeing this message. Is there anything else I need to do?

**Comment by bdmogal** [comment]
@pbo-cirus could you please check again - e.g. the pom.xml shows every single line changed. and its mostly whitespace changes.

**Comment by bdmogal** [comment]
Another thing to check is - the default length of the line is 120 characters, but seems like some files break it at 80, which causes more changes.

**Comment by pbo-cirus** [comment]
I just found out I committed with the wrong email id. I need to redo it with the right one.

**Pull request closed without merging**
